### ISSUE TITLE
Use local file instead of re-downloading XWAU2020.exe

### ISSUE THREAD

**Issue by GLM-NormandNadon** [dhollinger/lutris_installers#3]
I have the XWAU2020.exe file on the computer, I even placed it where Lutris would download it in the .cache folder.
Your installer always erases the folder and re-download the file...
Could you make it possible to select a local file for this one?... it is a huge file and I am actually trying to diagnose the installer.
Your installer made me download the upgrade 7 times tonight!

**Comment by dhollinger** [comment]
Are you installing via the file instead of from the website? The file is cached by lutris, but by default Lutris itself deletes those files at the end of an installation, successful or failed. I looked in the installer docs, there's nothing I can do to change that. You may have to ping the lutris team on discord in their #lutris_support channel.
